### ISSUE TITLE
Lazylibrarian will not update

### ISSUE THREAD

**Issue by Natteverf** [linuxserver/docker-lazylibrarian#17]
From the logs of the container:
03-May-2018 01:50:21 - WARNING :: UPDATES : versioncheck.py:logmsg:44 : Could not get the latest commit from github
03-May-2018 01:50:21 - INFO :: UPDATES : versioncheck.py:logmsg:40 : Unable to get latest version from GitHub
03-May-2018 01:50:22 - INFO :: UPDATES : versioncheck.py:logmsg:40 : Lazylibrarian is up to date

**Comment by homerr** [comment]
The container (as it is now) will pull the latest version from their Git repo and then build from that. Soon, this will change, but there is some work to do with that. We do not advise allowing containers to run their own updaters due to the nature of Docker, the update will be lost on restart but could leave your config files inaccessible to a previous version if updated.
